export { default as MyButton } from './components/MyButton'
export { default as PiXiDemo } from './components/PiXiDemo'
export { default as EchartsDemo } from './components/EchartsDemo'
export { default as WorkerDemo } from './components/WorkerDemo'
export { default as SvgJsDemo } from './components/SvgJsDemo'
export { default as SvgJsDemo2 } from './components/SvgJsDemo2'
export { default as TTTDemo } from './components/TTTDemo'
